=== chainjazz/chainjazz.github.io/xmlfs/recepti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/recepti" xmlns:tns="http://www.example.org/recepti" elementFormDefault="qualified">

    <complexType name="recepti">
    	<sequence>
    		<element name="proizvod" type="tns:proizvod" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    




    <element name="recepti" type="tns:recepti"></element>
    


    <complexType name="proizvod">
    	<sequence>
    		<element name="komentar" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="proizvod" type="tns:proizvod"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="naziv" type="string" use="required"></attribute>
    	<attribute name="tindeks" type="int"></attribute>
    	<attribute name="prelazni" type="boolean"></attribute>
    	<attribute name="operacija" type="tns:operacija"></attribute>
    	<attributeGroup ref="tns:PocetniSastojak"></attributeGroup>
    	<attribute name="optip" type="string"></attribute>
    	<attribute name="opparam" type="float">
    		<annotation>
    			<documentation>opparam

floating-point ratio of temperature to time of thermic process</documentation>
    		</annotation></attribute>
    </complexType>

    <simpleType name="kolicina">
    	<restriction base="float"></restriction>
    </simpleType>

    <simpleType name="jedinica">
    	<restriction base="NMTOKEN">
    		<enumeration value="kg"></enumeration>
    		<enumeration value="tsp"></enumeration>
    		<enumeration value="tbsp"></enumeration>
    		<enumeration value="l"></enumeration>
    		<enumeration value="ml"></enumeration>
    		<enumeration value="g"></enumeration>
    		<enumeration value="cup"></enumeration>
    		<enumeration value="oz"></enumeration>
    		<enumeration value="serving"></enumeration>
    		<enumeration value="piece"></enumeration>
    	</restriction>
    </simpleType>






    <simpleType name="operacija">
    	<restriction base="NMTOKEN">
    		<enumeration value="heat"></enumeration>
    		<enumeration value="whisk"></enumeration>
    		<enumeration value="mix"></enumeration>
    		<enumeration value="dip"></enumeration>
    		<enumeration value="deepfry"></enumeration>
    	</restriction>
    </simpleType>

    <attributeGroup name="PocetniSastojak">
    	<attribute name="jedinica" type="tns:jedinica"></attribute>
    	<attribute name="kolicina" type="tns:kolicina"></attribute>
    </attributeGroup>
</schema>

=== chainjazz/chainjazz.github.io/xmlfs/recepti.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="recepti.xsl"?>
<recepti:recepti xmlns:recepti="http://www.example.org/recepti" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/recepti recepti.xsd ">
  <recepti:proizvod naziv="Hleb" operacija="heat" opparam="9.5">
  	<recepti:komentar>recepti:komentar</recepti:komentar>
  	  		
  	<recepti:proizvod naziv="Korak1" operacija="mix">
  	
  		 	
		<recepti:proizvod naziv="oil" kolicina="78.0" jedinica="ml"></recepti:proizvod>
 		<recepti:proizvod naziv="flour" jedinica="g" kolicina="360.0"></recepti:proizvod>
		<recepti:proizvod naziv="baking powder" jedinica="tbsp" kolicina="1.0"></recepti:proizvod>
 		<recepti:proizvod naziv="salt" jedinica="tsp" kolicina="1.0"></recepti:proizvod>
 		<recepti:proizvod naziv="water" jedinica="cup" kolicina="1.0"></recepti:proizvod> 	
  	
  	
  	</recepti:proizvod>
  	
  	
  	
  </recepti:proizvod>
  
  <recepti:proizvod naziv="Onion rings" operacija="heat" opparam="9.5">
  	<recepti:komentar>Careful-hot-oil</recepti:komentar>
  	
  	
  	
  	<recepti:proizvod naziv="Korak1" operacija="deepfry">
  	
  		<recepti:proizvod naziv="battered-rings"  operacija="dip">
  	
  	
  	  		
  	<recepti:proizvod naziv="batter" operacija="mix">
  		<recepti:proizvod naziv="batter-base" operacija="whisk">
  			<recepti:proizvod naziv="sr-flour" jedinica="g" kolicina="150.0"></recepti:proizvod>
  			<recepti:proizvod naziv="sparkling water" jedinica="ml" kolicina="100.0"></recepti:proizvod>  			
  		</recepti:proizvod>  			
  		
  		<recepti:proizvod naziv="chives" jedinica="g" kolicina="45.0"></recepti:proizvod>
  		<recepti:proizvod naziv="turmeric" jedinica="tsp" kolicina="0.5"></recepti:proizvod>  		
   	</recepti:proizvod>
   	
   	
   	
   	<recepti:proizvod naziv="red-onion" jedinica="piece" kolicina="1.0">
   		<recepti:komentar>Sliced and peeled</recepti:komentar>
   	</recepti:proizvod>  	
  	
  	</recepti:proizvod>
  	
  	
  	</recepti:proizvod>
  	
  	
  	
  	<recepti:proizvod naziv="sizzling oil" operacija="heat">
   		<recepti:proizvod naziv="oil" kolicina="300.0" jedinica="ml"></recepti:proizvod>   	
   	</recepti:proizvod>
   	
  	<recepti:proizvod naziv="sea-salt" jedinica="tsp" kolicina="0.5"></recepti:proizvod>
  </recepti:proizvod>
  	
  	
  	
  
  
  	
  	


</recepti:recepti>
